---
title: "Test run"
output: html_document
date: "2024-06-05"
---

```{r}
in_path = "C:/Users/jacko/Documents/SeqBiomeML/SeqBiomeML/R/"
file_path <- list.files(in_path, full.names = TRUE)
for(f_path in file_path) { source(f_path) }
```


```{r}
# 94% of this data is 0s
meta = read.csv("C:/Users/jacko/Documents/SeqBiomeML/Data/16S_metadata.csv")
rsv = read.csv("C:/Users/jacko/Documents/SeqBiomeML/Data/16S_rsv.csv")
# Be careful when doing this as the rownames are not 1:nrow(meta). It will have gaps (e.g. 1, 2, 4, 5, ...). This can cause issue in downstream analysis. Issue occurs in case_weight_vctr
true_meta = meta[meta$INCLUDE == c("YES"), ] # Only selects samples that are supposed to be included for analysis
rownames(rsv) = rsv$taxa
rsv = rsv[, -1]
rsv = as.data.frame(t(rsv))
rsv = rsv[rownames(rsv) %in% true_meta$SampleID, ]
```


```{r}
# Read DESCRIPTION file to extract Imports
description_file <- "C:/Users/jacko/Downloads/SeqBiomeML_latest/SeqBiomeML/DESCRIPTION"
description <- readLines(description_file)
pkg = description[13:28]
pkg = pkg[-15]

for (i in pkg) {
  x = sub(",", "", i)
  y = trimws(x)
  if (!requireNamespace(y, quietly = TRUE)) {
    install.packages(y)
  }
  library(y, character.only = T)
}
```


```{r}
library(mRMRe)
library(glmnet)
library(Boruta)
out = run_ml_cv(dataset = comp_data, metadata = con_ath, outcome_colname = "ParticipantType", group_colname = "SubjectID", scale_method = c("clr", "pseudo", 1),  preprocess_methods = c("nzv", "center", "scale"), filter_features = T, filterFunList = list(test = "mrmr_filter", n = 100), find_feature_importance = F, feature_importance_method = "permutation", seed = 0, method = "rf")

out[[7]]
```


```{r}
out <- run_ml_nestedcv(comp_data, S_meta, method = "rf", outcome_colname = "ParticipantType", group_colname = "SubjectID", scale_method = list("clr", "pseudo", 1), preprocess_methods = c("nzv"), corrFunList = list(corr_method = "spearman", corr_thresh = 1, group_neg_corr = TRUE), filter_features = T, filterFunList = list(test = "rfe_filter"), outer_folds = NULL, resamp_method = "repeatedcv", n_outer_folds = 5, n_inner_folds = 10, cv_times = 10, training_frac = 0.80, hyperparameters = NULL, cross_val = NULL, perf_metric_function = NULL, perf_metric_name = NULL, class_weight = FALSE, find_feature_importance = FALSE, feature_importance_method = "permutation", jobs = 1, threads = 1, seed = 0)

lapply(out[[1]], function(x) x[[6]]) # to look at performance
lapply(out[[1]], function(x) x[[7]]) # to look at plots
```


```{r}
con_ath = true_meta
con_ath[con_ath$ParticipantType != "control", 2] = "Athlete"
comp_data <- rsv[rownames(rsv) %in% con_ath$SampleID, ]
```


```{r}
binary_meta = meta[meta$ParticipantType != "control", ]
rownames(binary_meta) <- seq(1, nrow(binary_meta))
binary_data = rsv[rownames(rsv) %in% binary_meta$SampleID, ]
```


```{r}
outcome_type = "binary"
method = "rf"
set.seed(0)
true_meta = S_meta
rsv = comp_data
library(progressr)
y = true_meta[["ParticipantType"]]
set.seed(0)
rsv <- randomize_feature_order(rsv) %>% as.data.frame()
rsv <- preprocess_samples(dataset = rsv, scale_method = list("clr", "pseudo", 1))
training_inds = get_partition_indices(y, training_frac = 0.8)
train_data <- rsv[training_inds, ]
test_data <- rsv[-training_inds, ]
train_metadata <- true_meta[training_inds, ]
test_metadata <- true_meta[-training_inds, ]
pre = preprocess_features(train_data, test_data, outcome_colname = "ParticipantType", preprocess_methods = c("nzv"), corrFunList = list(corr_method = "spearman", corr_thresh = 1, group_neg_corr = TRUE))
train_data = pre[[1]]
test_data = pre[[2]]
filt_dataset <- filter_features_main(train_data = train_data, train_metadata = train_metadata, test_data = test_data, outcome_colname = "ParticipantType", filterFunList = list(test = "boruta_filter", n = 100, maxRuns = 100), outcome_type = outcome_type)
train_data = filt_dataset[[1]]
test_data = filt_dataset[[2]]
hyperparameters <- get_hyperparams_list(train_data, method)
tune_grid <- get_tuning_grid(hyperparameters, method)
perf_metric_function <- get_perf_metric_fn(outcome_type)
perf_metric_name <- get_perf_metric_name(outcome_type)
cross_val = define_cv_unnested(resamp_method = "cv",
        train_data = train_data,
        train_metadata = train_metadata,
        outcome_colname = "ParticipantType",
        hyperparams_list = hyperparameters,
        perf_metric_function = perf_metric_function,
        kfold = 5,
        cv_times = 0,
        seed = 0,
        groups = NULL,
        group_partitions = NULL,
        class_probs = TRUE)
trained_model_caret = train_model(
      train_data = train_data,
      train_metadata = train_metadata,
      outcome_colname = "ParticipantType",
      method = method,
      cv = cross_val,
      perf_metric_name = perf_metric_name,
      tune_grid = tune_grid,
      weights = NULL)
performance_tbl <- get_performance_tbl(
      trained_model = trained_model_caret,
      test_data = test_data,
      test_metadata = test_metadata,
      outcome_colname = "ParticipantType",
      perf_metric_function = perf_metric_function,
      perf_metric_name = perf_metric_name,
      method = method,
      class_probs = T)
roc_out = plot_main(
      trained_model = trained_model_caret,
      test_data = test_data,
      test_metadata = test_metadata,
      outcome_colname = "ParticipantType",
      method = method,
      outcome_type = outcome_type)
feat_imp = feature_importance_main(
            feature_importance_method,
            trained_model = trained_model_caret,
            test_data = test_data,
            test_metadata = test_metadata,
            outcome_colname = "ParticipantType",
            perf_metric_function = perf_metric_function,
            perf_metric_name = perf_metric_name,
            class_probs = T,
            method = method,
            seed = 0,
            nperms = 100,
            threads = 1,
            performance_table = performance_tbl)
# pre
# test_data
# test_metadata
# cross_val
# trained_model_caret
performance_tbl
roc_out
feat_imp
# test = feat_imp[feat_imp$pvalue > 0.95, ]
# test
```


```{r}
# none of the below worked
library(shapper)
library(shapr)
library(shapley)
library(reticulate) # allows the use of python in R, it does work
```


```{r}
groups = S_meta[["SubjectID"]]
outcome_colname = "ParticipantType"
dataset <- preprocess_samples(dataset = comp_data, scale_method = list("clr", "pseudo", 1))
outer_folds <- define_outer_folds(metadata = S_meta, outcome_colname = outcome_colname, outer_fold = 5, groups = groups, seed = 0)
test <- parallel::mclapply(
  seq_along(outer_folds), 
  function(out_fold) {
    tryCatch(
      {
        nestedcvCore(
          dataset = dataset,
          metadata = S_meta,
          groups = groups,
          method = "rf",
          preprocess_methods = c("nzv"),
          corrFunList = list(corr_method = "spearman", corr_thresh = 1, group_neg_corr = TRUE),
          outcome_type = "binary",
          class_probs = TRUE,
          outcome_colname = outcome_colname,
          out_fold = out_fold,
          outer_folds = outer_folds,
          hyperparameters = NULL,
          resamp_method = "cv",
          perf_metric_name = NULL,
          perf_metric_function = NULL,
          n_inner_folds = 5,
          cv_times = 0,
          filter_features = TRUE,
          filterFunList = list(test = "mrmr_filter", n = 100),
          threads = 1,
          seed = 0,
          class_weight = F
        )
      }, 
      error = function(e) {
        print(e)
        NULL
      }
    )
  }, 
  mc.cores = 1, 
  mc.allow.recursive = FALSE
)

names(test) <- paste0("Fold", seq(1, length(test)))

test[[5]][[6]]
```


```{r}
test1 = nestedcvCore(
        dataset = dataset,
        metadata = S_meta,
        groups = groups,
        method = "rf",
        preprocess_methods = c("nzv"),
        corrFunList = list(corr_method = "spearman", corr_thresh = 1, group_neg_corr = TRUE),
        outcome_type = "binary",
        class_probs = TRUE,
        outcome_colname = outcome_colname,
        out_fold = 4,
        outer_folds = outer_folds,
        hyperparameters = NULL,
        resamp_method = "cv",
        perf_metric_name = NULL,
        perf_metric_function = NULL,
        n_inner_folds = 5,
        cv_times = 0,
        filter_features = TRUE,
        filterFunList = list(test = "mrmr_filter", n = 100),
        threads = 1,
        seed = 0,
        class_weight = F
      )
```


```{r}
### for dealing with test sets that only have one factor
pred_type <- "raw"
pred_type <- "prob"
preds <- stats::predict(test[[4]][[1]], test[[4]][[2]], type = pred_type)
uniq_obs <- unique(test[[4]][[3]][["ParticipantType"]]) ### replaced pull and removed as.character(trained_model$pred$obs), all factors should be in outcome_colname

###### this is the changed section
# Add missing level if only one factor level is present
if (length(uniq_obs) == 1) {
  missinglevel <- test[[5]][[1]]$pred$obs %>%
    unique() %>%
    setdiff(uniq_obs) %>%
    as.character() # extracts missing factor
  uniq_obs <- c(uniq_obs, missinglevel)
}
######

obs <- factor(test[[4]][[3]][[outcome_colname]], levels = uniq_obs)
if (class_probs) {
  pred_class <- factor(names(preds)[apply(preds, 1, which.max)], levels = uniq_obs)
  perf_met <- perf_metric_function(data.frame(obs = obs, pred = pred_class, preds), lev = uniq_obs)
} else {
  perf_met <- perf_metric_function(data.frame(obs = obs, pred = preds), lev = uniq_obs)
}
return(perf_met)
```


```{r}
# for viewing saved ggplots
r_results <- load("../Data/16S_rsv/r_resultst.RData")

library(magick)
r_plot1 = image_read("../Data/16S_rsv/r_plot1.png")
r_plot2 = image_read("../Data/16S_rsv/r_plot2_unique.png")
plot3 = image_read("../Data/16S_rsv/r_plot3_unique.png")
plot4 = image_read("../Data/16S_rsv/r_plot4.png")
plot5 = image_read("../Data/16S_rsv/r_plot5.png")
```


```{r}
# for comparing performance for models
# gets summary statistics for the parameters of the predictive model
sum_list = lapply(AUC_list, summary)
r_sum_data = as.data.frame(do.call(rbind, sum_list))
s_sum_data = as.data.frame(do.call(rbind, sum_list))
g_sum_data = as.data.frame(do.call(rbind, sum_list))
ms_sum_data = as.data.frame(do.call(rbind, sum_list))

# gets the data ready for kruskal test
scl_data = data.frame(scale_method = rep(names(scl_list), times = sapply(scl_list, length)), AUC = unlist(scl_list))
flt_data = data.frame(fs_method = rep(names(flt_list), times = sapply(flt_list, length)), AUC = unlist(flt_list))
mdl_data = data.frame(model = rep(names(mdl_list), times = sapply(mdl_list, length)), AUC = unlist(mdl_list))

r_param_data = list(scl_data, flt_data, mdl_data)
s_param_data = list(scl_data, flt_data, mdl_data)
g_param_data = list(scl_data, flt_data, mdl_data)
ms_param_data = list(scl_data, flt_data, mdl_data)

save(r_sum_data, r_param_data,  file = "r_predictive_model_results.RData")

############ Run the rest once all the individual results are gathered ###############

# gets the mean summary statistics across all datsets
full_sum_data = rbind(s_sum_data, g_sum_data, r_sum_data, ms_sum_data)
full_sum_data$Group = c(rownames(s_sum_data), rownames(g_sum_data), rownames(r_sum_data), rownames(ms_sum_data))
mean_sum_data = lapply(split(full_sum_data, full_sum_data$Group), function(x) colMeans(x[, 1:6]))
mean_sum_data = as.data.frame(do.call(rbind, mean_sum_data))
mean_var_auc = mean(apply(mean_sum_data, 1, function(x) x[6] - x[1]))

# gets the p-value and difference between the models across all datasets
rscl_data = do.call(cbind, r_param_data[[1]])
sscl_data = do.call(cbind, s_param_data[[1]])
gscl_data = do.call(cbind, g_param_data[[1]])
msscl_data = do.call(cbind, ms_param_data[[1]])
scl_data = as.data.frame(rbind(rscl_data, sscl_data, gscl_data, msscl_data))
scl_data$AUC = as.numeric(scl_data$AUC)

rflt_data = do.call(cbind, r_param_data[[2]])
sflt_data = do.call(cbind, s_param_data[[2]])
gflt_data = do.call(cbind, g_param_data[[2]])
msflt_data = do.call(cbind, ms_param_data[[2]])
flt_data = as.data.frame(rbind(rflt_data, sflt_data, gflt_data, msflt_data))
flt_data$AUC = as.numeric(flt_data$AUC)

rmdl_data = do.call(cbind, r_param_data[[3]])
smdl_data = do.call(cbind, s_param_data[[3]])
gmdl_data = do.call(cbind, g_param_data[[3]])
msmdl_data = do.call(cbind, ms_param_data[[3]])
mdl_data = as.data.frame(rbind(rmdl_data, smdl_data, gmdl_data, msmdl_data))
mdl_data$AUC = as.numeric(mdl_data$AUC)

# for normally distributed data
#aov_result = aov(AUC ~ model, data = mdl_data)
#summary(aov_result)
#TukeyHSD(aov_result)
# for non-parametric data
library(FSA)
ktest = kruskal.test(AUC ~ scale_method, data = scl_data)
dtest = dunnTest(AUC ~ scale_method, data = scl_data, method = "bonferroni")
scl_comp = list(krsukal = ktest, dunn = dtest)
ktest = kruskal.test(AUC ~ fs_method, data = flt_data)
dtest = dunnTest(AUC ~ fs_method, data = flt_data, method = "bonferroni")
flt_comp = list(krsukal = ktest, dunn = dtest)
ktest = kruskal.test(AUC ~ model, data = mdl_data)
dtest = dunnTest(AUC ~ model, data = mdl_data, method = "bonferroni")
mdl_comp = list(krsukal = ktest, dunn = dtest)

colnames(scl_data)[1] = "method"
colnames(flt_data)[1] = "method"
colnames(mdl_data)[1] = "method"
method_data = rbind(scl_data, flt_data, mdl_data)
method_data$SubGroup = apply(method_data, 1, function(x) case_when(
  x[["method"]] %in% c("clr", "tss", "rclr") ~ "Scale Method",
  x[["method"]] %in% c("mrmr_filter", "glm_filter", "boruta_filter") ~ "Feature Selection",
  x[["method"]] %in% c("rf", "glmnet", "kknn", "svmRadial") ~ "Model Approach"
))
method_data$method <- factor(method_data$method, levels = c("clr", "tss", "rclr", "mrmr_filter", "glm_filter", "boruta_filter", "rf", "glmnet", "kknn", "svmRadial"))

method_plot <- ggplot(method_data, aes(x = method, y = AUC, fill = SubGroup)) +
  geom_boxplot(outlier.shape = NA, width = 0.4, lwd = 0.8, position = position_dodge(width = 0.75)) +  
  geom_jitter(color = "black", alpha = 0.1, position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.75)) +
  scale_fill_viridis(discrete = TRUE, option = "Q", begin = 0.4, end = 1) + 
  labs(x = 'Model', y = 'AUC Value', title = 'Comparison of AUC for Different Models') +
  theme_minimal() +
  theme(legend.position = 'top')


dunn = rbind(scl_comp[[2]]$res, flt_comp[[2]]$res, mdl_comp[[2]]$res)
krus = rbind(Scale_Method = scl_comp[[1]]$p.value, Feature_Selection = flt_comp[[1]]$p.value, Model_Approach = mdl_comp[[1]]$p.value)
save(dunn, krus, mean_sum_data, mean_var_auc, file = "predictive_model_res.RData")
ggsave("predictive_model_plot.png", plot = method_plot, width = 12, height = 7, units = "in")
```


```{r}
# formatting into one grid 
library(gridExtra)
library(grid)
library(ggplot2)

# grid plot
r_grid_img1 <- rasterGrob(r_plot1, interpolate=TRUE)
s_grid_img1 <- rasterGrob(g_plot1, interpolate=TRUE)
g_grid_img1 <- rasterGrob(s_plot1, interpolate=TRUE)
ms_grid_img1 <- rasterGrob(ms_plot1, interpolate=TRUE)
grid <- grid.arrange(r_grid_img1, s_grid_img1, g_grid_img1, ms_grid_img1, nrow=4)
ggsave("plot1_grid.png", plot = grid, width = 10, height = 10)


# grid table for top 5 most frequent features
r_freq_5 = rbind(freq_out[[2]], freq_out[[3]][1:4, ])
s_freq_5 = rbind(freq_out[[2]], freq_out[[3]][1:4, ])
g_freq_5 = rbind(freq_out[[2]], freq_out[[3]][1:4, ])
ms_freq_5 = rbind(freq_out[[2]], freq_out[[3]][1:4, ])

grid_table1 = rbind(r_freq_5, s_freq_5, g_freq_5, ms_freq_5)


# grid table for top 5 most significant features (by most frequent significant features)
r_sig_5 = count_sig_colour[1:5, ]
s_sig_5 = count_sig_colour[1:5, ]
g_sig_5 = count_sig_colour[1:5, ]
ms_sig_5 = count_sig_colour[1:5, ]

save(freq_out, sig_features, sig_data_colour, count_sig_colour, best_auc, best_sig, group_best, s_freq_5, s_sig_5, file = "s_resultst.RData")

# comparison of relative abundance between groups
S_species = data.frame(t(apply(S_species, 1, function(x) x/sum(x))))
sig_12 = as.character(head(count_sig_colour, 12)$Var1)
sig_12 = sapply(sig_12, function (x) gsub("-", ".", x))
sig_12 = sapply(sig_12, function (x) gsub(" ", ".", x))
best_species = S_species[, sig_12]
# adds a group column (Control/Athlete)
group_best = cbind(best_species, Group = S_meta$ParticipantType)
group_best[group_best$Group != "control", 13] = "athlete"

s_ra_res = apply(group_best[, 1:12], 2, function(x) t.test(x ~ group_best$Group)$p.value)

save(freq_out, sig_features, sig_data_colour, count_sig_colour, best_auc, best_sig, group_best, s_freq_5, s_sig_5, s_ra_res, file = "s_resultst.RData")


# comparison of relative abundance between groups
S_rsv = data.frame(t(apply(S_rsv, 1, function(x) x/sum(x))))
sig_12 = as.character(head(count_sig_colour, 12)$Var1)
sig_12 = sapply(sig_12, function (x) gsub("-", ".", x))
sig_12 = sapply(sig_12, function (x) gsub(" ", ".", x))
sig_12 = sapply(sig_12, function (x) gsub("#", ".", x))
sig_12 = sapply(sig_12, function (x) gsub("\\[|\\]", ".", x))
best_species = S_rsv[, sig_12]
# adds a group column (Control/Athlete)
group_best = cbind(best_species, Group = S_meta$ParticipantType)
group_best[group_best$Group != "control", 13] = "athlete"

r_ra_res = apply(group_best[, 1:12], 2, function(x) t.test(x ~ group_best$Group)$p.value)

save(freq_out, sig_features, sig_data_colour, count_sig_colour, best_auc, best_sig, group_best, r_freq_5, r_sig_5, r_ra_res, file = "r_resultst.RData")
```


```{r}
library(dplyr)
grid_tbl1 = rbind(r_freq_5, s_freq_5, g_freq_5)
grid_tbl2 = rbind(r_sig_5, s_sig_5, g_sig_5)
# binding features and p-values
r_feat_p = rbind(names(r_ra_res), formatC(r_ra_res, format = "e", digits = 2))
s_feat_p = rbind(names(s_ra_res), formatC(s_ra_res, format = "e", digits = 2))
g_feat_p = rbind(names(g_ra_res), formatC(g_ra_res, format = "e", digits = 2))
ms_feat_p = rbind(names(ms_ra_res), formatC(ms_ra_res, format = "e", digits = 2))
grid_tbl3 = as.data.frame(rbind(r_feat_p, s_feat_p, g_feat_p))
colnames(grid_tbl3) = paste0("Significant Feature ", seq(1:12))

write.table(t(ms_feat_p), "clipboard", sep = "\t", row.names = FALSE, col.names = TRUE)
```

